spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction2?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&jdbcCompliantTruncation=false
    username: root
    password: ''
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 3002